{"metadata":{"kernelspec":{"language":"python","display_name":"Python 3","name":"python3"},"language_info":{"name":"python","version":"3.10.13","mimetype":"text/x-python","codemirror_mode":{"name":"ipython","version":3},"pygments_lexer":"ipython3","nbconvert_exporter":"python","file_extension":".py"},"kaggle":{"accelerator":"none","dataSources":[],"dockerImageVersionId":30698,"isInternetEnabled":true,"language":"python","sourceType":"notebook","isGpuEnabled":false}},"nbformat_minor":4,"nbformat":4,"cells":[{"cell_type":"code","source":"!pip install cupy-cuda102 cupy-cuda110","metadata":{"execution":{"iopub.status.busy":"2024-05-01T08:25:43.441954Z","iopub.execute_input":"2024-05-01T08:25:43.444160Z","iopub.status.idle":"2024-05-01T08:26:10.964409Z","shell.execute_reply.started":"2024-05-01T08:25:43.444039Z","shell.execute_reply":"2024-05-01T08:26:10.963072Z"},"trusted":true},"execution_count":7,"outputs":[{"name":"stdout","text":"Requirement already satisfied: cupy-cuda102 in /opt/conda/lib/python3.10/site-packages (12.3.0)\nCollecting cupy-cuda110\n  Downloading cupy_cuda110-12.3.0-cp310-cp310-manylinux2014_x86_64.whl.metadata (2.7 kB)\nRequirement already satisfied: numpy<1.29,>=1.20 in /opt/conda/lib/python3.10/site-packages (from cupy-cuda102) (1.26.4)\nRequirement already satisfied: fastrlock>=0.5 in /opt/conda/lib/python3.10/site-packages (from cupy-cuda102) (0.8.2)\nDownloading cupy_cuda110-12.3.0-cp310-cp310-manylinux2014_x86_64.whl (79.5 MB)\n\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m79.5/79.5 MB\u001b[0m \u001b[31m5.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m:00:01\u001b[0m00:01\u001b[0m\n\u001b[?25hInstalling collected packages: cupy-cuda110\nSuccessfully installed cupy-cuda110-12.3.0\n","output_type":"stream"}]},{"cell_type":"code","source":"!pip install cupy","metadata":{"execution":{"iopub.status.busy":"2024-05-01T08:26:10.967180Z","iopub.execute_input":"2024-05-01T08:26:10.967636Z","iopub.status.idle":"2024-05-01T08:26:20.966189Z","shell.execute_reply.started":"2024-05-01T08:26:10.967569Z","shell.execute_reply":"2024-05-01T08:26:20.964476Z"},"trusted":true},"execution_count":8,"outputs":[{"name":"stdout","text":"Collecting cupy\n  Using cached cupy-13.1.0.tar.gz (3.5 MB)\n  Preparing metadata (setup.py) ... \u001b[?25ldone\n\u001b[?25hRequirement already satisfied: numpy<1.29,>=1.22 in /opt/conda/lib/python3.10/site-packages (from cupy) (1.26.4)\nRequirement already satisfied: fastrlock>=0.5 in /opt/conda/lib/python3.10/site-packages (from cupy) (0.8.2)\nBuilding wheels for collected packages: cupy\n  Building wheel for cupy (setup.py) ... \u001b[?25lerror\n  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n  \n  \u001b[31m×\u001b[0m \u001b[32mpython setup.py bdist_wheel\u001b[0m did not run successfully.\n  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n  \u001b[31m╰─>\u001b[0m \u001b[31m[63 lines of output]\u001b[0m\n  \u001b[31m   \u001b[0m Generating cache key from header files...\n  \u001b[31m   \u001b[0m Cache key (1527 files matching /tmp/pip-install-4ym0fxay/cupy_61fe7046673643b6bebd63260ba5e993/cupy/_core/include/**): 350066fe42f6a49a3bd1d8ea0614e4f427c3c517\n  \u001b[31m   \u001b[0m Clearing directory: /tmp/pip-install-4ym0fxay/cupy_61fe7046673643b6bebd63260ba5e993/cupy/.data\n  \u001b[31m   \u001b[0m \n  \u001b[31m   \u001b[0m -------- Configuring Module: cuda --------\n  \u001b[31m   \u001b[0m /tmp/tmpdm95cc3n/a.cpp:1:10: fatal error: cublas_v2.h: No such file or directory\n  \u001b[31m   \u001b[0m     1 | #include <cublas_v2.h>\n  \u001b[31m   \u001b[0m       |          ^~~~~~~~~~~~~\n  \u001b[31m   \u001b[0m compilation terminated.\n  \u001b[31m   \u001b[0m command '/usr/bin/gcc' failed with exit code 1\n  \u001b[31m   \u001b[0m /tmp/tmpso9wco3t/a.cpp:2:18: fatal error: cuda_runtime_api.h: No such file or directory\n  \u001b[31m   \u001b[0m     2 |         #include <cuda_runtime_api.h>\n  \u001b[31m   \u001b[0m       |                  ^~~~~~~~~~~~~~~~~~~~\n  \u001b[31m   \u001b[0m compilation terminated.\n  \u001b[31m   \u001b[0m **************************************************\n  \u001b[31m   \u001b[0m *** WARNING: Cannot check compute capability\n  \u001b[31m   \u001b[0m command '/usr/bin/gcc' failed with exit code 1\n  \u001b[31m   \u001b[0m **************************************************\n  \u001b[31m   \u001b[0m \n  \u001b[31m   \u001b[0m ************************************************************\n  \u001b[31m   \u001b[0m * CuPy Configuration Summary                               *\n  \u001b[31m   \u001b[0m ************************************************************\n  \u001b[31m   \u001b[0m \n  \u001b[31m   \u001b[0m Build Environment:\n  \u001b[31m   \u001b[0m   Include directories: ['/tmp/pip-install-4ym0fxay/cupy_61fe7046673643b6bebd63260ba5e993/cupy/_core/include/cupy/_cccl/libcudacxx', '/tmp/pip-install-4ym0fxay/cupy_61fe7046673643b6bebd63260ba5e993/cupy/_core/include/cupy/_cccl/thrust', '/tmp/pip-install-4ym0fxay/cupy_61fe7046673643b6bebd63260ba5e993/cupy/_core/include/cupy/_cccl/cub', '/tmp/pip-install-4ym0fxay/cupy_61fe7046673643b6bebd63260ba5e993/cupy/_core/include']\n  \u001b[31m   \u001b[0m   Library directories: []\n  \u001b[31m   \u001b[0m   nvcc command       : (not found)\n  \u001b[31m   \u001b[0m   hipcc command      : (not found)\n  \u001b[31m   \u001b[0m \n  \u001b[31m   \u001b[0m Environment Variables:\n  \u001b[31m   \u001b[0m   CFLAGS          : (none)\n  \u001b[31m   \u001b[0m   LDFLAGS         : (none)\n  \u001b[31m   \u001b[0m   LIBRARY_PATH    : :/opt/conda/lib\n  \u001b[31m   \u001b[0m   CUDA_PATH       : (none)\n  \u001b[31m   \u001b[0m   NVCC            : (none)\n  \u001b[31m   \u001b[0m   HIPCC           : (none)\n  \u001b[31m   \u001b[0m   ROCM_HOME       : (none)\n  \u001b[31m   \u001b[0m \n  \u001b[31m   \u001b[0m Modules:\n  \u001b[31m   \u001b[0m   cuda      : No\n  \u001b[31m   \u001b[0m     -> Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'cufft.h', 'curand.h', 'cusparse.h']\n  \u001b[31m   \u001b[0m     -> Check your CFLAGS environment variable.\n  \u001b[31m   \u001b[0m \n  \u001b[31m   \u001b[0m ERROR: CUDA could not be found on your system.\n  \u001b[31m   \u001b[0m \n  \u001b[31m   \u001b[0m HINT: You are trying to build CuPy from source, which is NOT recommended for general use.\n  \u001b[31m   \u001b[0m       Please consider using binary packages instead.\n  \u001b[31m   \u001b[0m \n  \u001b[31m   \u001b[0m Please refer to the Installation Guide for details:\n  \u001b[31m   \u001b[0m https://docs.cupy.dev/en/stable/install.html\n  \u001b[31m   \u001b[0m \n  \u001b[31m   \u001b[0m ************************************************************\n  \u001b[31m   \u001b[0m \n  \u001b[31m   \u001b[0m Traceback (most recent call last):\n  \u001b[31m   \u001b[0m   File \"<string>\", line 2, in <module>\n  \u001b[31m   \u001b[0m   File \"<pip-setuptools-caller>\", line 34, in <module>\n  \u001b[31m   \u001b[0m   File \"/tmp/pip-install-4ym0fxay/cupy_61fe7046673643b6bebd63260ba5e993/setup.py\", line 94, in <module>\n  \u001b[31m   \u001b[0m     ext_modules = cupy_setup_build.get_ext_modules(True, ctx)\n  \u001b[31m   \u001b[0m   File \"/tmp/pip-install-4ym0fxay/cupy_61fe7046673643b6bebd63260ba5e993/install/cupy_builder/cupy_setup_build.py\", line 475, in get_ext_modules\n  \u001b[31m   \u001b[0m     extensions = make_extensions(ctx, compiler, use_cython)\n  \u001b[31m   \u001b[0m   File \"/tmp/pip-install-4ym0fxay/cupy_61fe7046673643b6bebd63260ba5e993/install/cupy_builder/cupy_setup_build.py\", line 328, in make_extensions\n  \u001b[31m   \u001b[0m     raise Exception('Your CUDA environment is invalid. '\n  \u001b[31m   \u001b[0m Exception: Your CUDA environment is invalid. Please check above error log.\n  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n  \n  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n\u001b[31m  ERROR: Failed building wheel for cupy\u001b[0m\u001b[31m\n\u001b[0m\u001b[?25h  Running setup.py clean for cupy\n  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n  \n  \u001b[31m×\u001b[0m \u001b[32mpython setup.py clean\u001b[0m did not run successfully.\n  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n  \u001b[31m╰─>\u001b[0m \u001b[31m[63 lines of output]\u001b[0m\n  \u001b[31m   \u001b[0m Generating cache key from header files...\n  \u001b[31m   \u001b[0m Cache key (1527 files matching /tmp/pip-install-4ym0fxay/cupy_61fe7046673643b6bebd63260ba5e993/cupy/_core/include/**): 350066fe42f6a49a3bd1d8ea0614e4f427c3c517\n  \u001b[31m   \u001b[0m Clearing directory: /tmp/pip-install-4ym0fxay/cupy_61fe7046673643b6bebd63260ba5e993/cupy/.data\n  \u001b[31m   \u001b[0m \n  \u001b[31m   \u001b[0m -------- Configuring Module: cuda --------\n  \u001b[31m   \u001b[0m /tmp/tmp6imvkq1b/a.cpp:1:10: fatal error: cublas_v2.h: No such file or directory\n  \u001b[31m   \u001b[0m     1 | #include <cublas_v2.h>\n  \u001b[31m   \u001b[0m       |          ^~~~~~~~~~~~~\n  \u001b[31m   \u001b[0m compilation terminated.\n  \u001b[31m   \u001b[0m command '/usr/bin/gcc' failed with exit code 1\n  \u001b[31m   \u001b[0m /tmp/tmpg7qsyelp/a.cpp:2:18: fatal error: cuda_runtime_api.h: No such file or directory\n  \u001b[31m   \u001b[0m     2 |         #include <cuda_runtime_api.h>\n  \u001b[31m   \u001b[0m       |                  ^~~~~~~~~~~~~~~~~~~~\n  \u001b[31m   \u001b[0m compilation terminated.\n  \u001b[31m   \u001b[0m **************************************************\n  \u001b[31m   \u001b[0m *** WARNING: Cannot check compute capability\n  \u001b[31m   \u001b[0m command '/usr/bin/gcc' failed with exit code 1\n  \u001b[31m   \u001b[0m **************************************************\n  \u001b[31m   \u001b[0m \n  \u001b[31m   \u001b[0m ************************************************************\n  \u001b[31m   \u001b[0m * CuPy Configuration Summary                               *\n  \u001b[31m   \u001b[0m ************************************************************\n  \u001b[31m   \u001b[0m \n  \u001b[31m   \u001b[0m Build Environment:\n  \u001b[31m   \u001b[0m   Include directories: ['/tmp/pip-install-4ym0fxay/cupy_61fe7046673643b6bebd63260ba5e993/cupy/_core/include/cupy/_cccl/libcudacxx', '/tmp/pip-install-4ym0fxay/cupy_61fe7046673643b6bebd63260ba5e993/cupy/_core/include/cupy/_cccl/thrust', '/tmp/pip-install-4ym0fxay/cupy_61fe7046673643b6bebd63260ba5e993/cupy/_core/include/cupy/_cccl/cub', '/tmp/pip-install-4ym0fxay/cupy_61fe7046673643b6bebd63260ba5e993/cupy/_core/include']\n  \u001b[31m   \u001b[0m   Library directories: []\n  \u001b[31m   \u001b[0m   nvcc command       : (not found)\n  \u001b[31m   \u001b[0m   hipcc command      : (not found)\n  \u001b[31m   \u001b[0m \n  \u001b[31m   \u001b[0m Environment Variables:\n  \u001b[31m   \u001b[0m   CFLAGS          : (none)\n  \u001b[31m   \u001b[0m   LDFLAGS         : (none)\n  \u001b[31m   \u001b[0m   LIBRARY_PATH    : :/opt/conda/lib\n  \u001b[31m   \u001b[0m   CUDA_PATH       : (none)\n  \u001b[31m   \u001b[0m   NVCC            : (none)\n  \u001b[31m   \u001b[0m   HIPCC           : (none)\n  \u001b[31m   \u001b[0m   ROCM_HOME       : (none)\n  \u001b[31m   \u001b[0m \n  \u001b[31m   \u001b[0m Modules:\n  \u001b[31m   \u001b[0m   cuda      : No\n  \u001b[31m   \u001b[0m     -> Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'cufft.h', 'curand.h', 'cusparse.h']\n  \u001b[31m   \u001b[0m     -> Check your CFLAGS environment variable.\n  \u001b[31m   \u001b[0m \n  \u001b[31m   \u001b[0m ERROR: CUDA could not be found on your system.\n  \u001b[31m   \u001b[0m \n  \u001b[31m   \u001b[0m HINT: You are trying to build CuPy from source, which is NOT recommended for general use.\n  \u001b[31m   \u001b[0m       Please consider using binary packages instead.\n  \u001b[31m   \u001b[0m \n  \u001b[31m   \u001b[0m Please refer to the Installation Guide for details:\n  \u001b[31m   \u001b[0m https://docs.cupy.dev/en/stable/install.html\n  \u001b[31m   \u001b[0m \n  \u001b[31m   \u001b[0m ************************************************************\n  \u001b[31m   \u001b[0m \n  \u001b[31m   \u001b[0m Traceback (most recent call last):\n  \u001b[31m   \u001b[0m   File \"<string>\", line 2, in <module>\n  \u001b[31m   \u001b[0m   File \"<pip-setuptools-caller>\", line 34, in <module>\n  \u001b[31m   \u001b[0m   File \"/tmp/pip-install-4ym0fxay/cupy_61fe7046673643b6bebd63260ba5e993/setup.py\", line 94, in <module>\n  \u001b[31m   \u001b[0m     ext_modules = cupy_setup_build.get_ext_modules(True, ctx)\n  \u001b[31m   \u001b[0m   File \"/tmp/pip-install-4ym0fxay/cupy_61fe7046673643b6bebd63260ba5e993/install/cupy_builder/cupy_setup_build.py\", line 475, in get_ext_modules\n  \u001b[31m   \u001b[0m     extensions = make_extensions(ctx, compiler, use_cython)\n  \u001b[31m   \u001b[0m   File \"/tmp/pip-install-4ym0fxay/cupy_61fe7046673643b6bebd63260ba5e993/install/cupy_builder/cupy_setup_build.py\", line 328, in make_extensions\n  \u001b[31m   \u001b[0m     raise Exception('Your CUDA environment is invalid. '\n  \u001b[31m   \u001b[0m Exception: Your CUDA environment is invalid. Please check above error log.\n  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n  \n  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n\u001b[31m  ERROR: Failed cleaning build dir for cupy\u001b[0m\u001b[31m\n\u001b[0mFailed to build cupy\n\u001b[31mERROR: Could not build wheels for cupy, which is required to install pyproject.toml-based projects\u001b[0m\u001b[31m\n\u001b[0m","output_type":"stream"}]},{"cell_type":"code","source":"from sklearn.pipeline import make_pipeline\nimport pandas as pd\nimport matplotlib.pyplot as plt\nfrom sklearn.metrics import classification_report\nfrom sklearn.preprocessing import LabelEncoder\nimport numpy as np\nfrom pprint import pprint\nimport json\nimport wandb\nfrom sklearn.model_selection import ParameterGrid\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.preprocessing import StandardScaler\nimport xgboost as xgb\nimport lightgbm as lgb\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.svm import SVC\nfrom sklearn.tree import DecisionTreeClassifier\nfrom sklearn.ensemble import RandomForestClassifier\nfrom sklearn.neighbors import KNeighborsClassifier\nimport threading\nimport cupy as cp\nimport warnings\nfrom dotenv import load_dotenv\nfrom tqdm import tqdm\nimport matplotlib as mpl\nfrom sklearn.pipeline import Pipeline, make_pipeline\nfrom typing import *\nimport seaborn as sns\nfrom sklearn.model_selection import GridSearchCV, RandomizedSearchCV\nimport math\nimport os\nimport random\nfrom sklearn.decomposition import PCA, IncrementalPCA\nfrom sklearn import datasets\nfrom wandb.lightgbm import wandb_callback, log_summary\nimport logging\nimport time\nfrom sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis\nfrom sklearn.naive_bayes import GaussianNB\nfrom sklearn.ensemble import AdaBoostClassifier\nfrom sklearn.neural_network import MLPClassifier\nfrom sklearn.gaussian_process import GaussianProcessClassifier\nfrom joblib import dump\nfrom wandb.xgboost import WandbCallback\n\nload_dotenv()\nplt.style.use(\"ggplot\")\nPROJECT_NAME = \"Dimensionality-Reduction\" # os.getenv(\"PROJECT_NAME\")\nlogging.getLogger(\"lightgbm\").setLevel(logging.WARNING)\nlogging.getLogger(\"wandb\").setLevel(logging.ERROR)\nos.environ[\"WANDB_SILENT\"] = \"true\"\nwarnings.filterwarnings(\"ignore\")\nrun = str(time.time())\nRANDOM_STATE = 0\nrandom.seed(RANDOM_STATE)\nnp.random.seed(RANDOM_STATE)","metadata":{"_uuid":"8f2839f25d086af736a60e9eeb907d3b93b6e0e5","_cell_guid":"b1076dfc-b9ad-4769-8c92-a6c4dae69d19","execution":{"iopub.status.busy":"2024-05-01T08:02:56.289811Z","iopub.execute_input":"2024-05-01T08:02:56.290392Z","iopub.status.idle":"2024-05-01T08:02:56.365158Z","shell.execute_reply.started":"2024-05-01T08:02:56.290340Z","shell.execute_reply":"2024-05-01T08:02:56.363298Z"},"trusted":true},"execution_count":3,"outputs":[{"traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)","Cell \u001b[0;32mIn[3], line 21\u001b[0m\n\u001b[1;32m     19\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01msklearn\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mneighbors\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m KNeighborsClassifier\n\u001b[1;32m     20\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mthreading\u001b[39;00m\n\u001b[0;32m---> 21\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mcupy\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m \u001b[38;5;21;01mcp\u001b[39;00m\n\u001b[1;32m     22\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mwarnings\u001b[39;00m\n\u001b[1;32m     23\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mdotenv\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m load_dotenv\n","\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'cupy'"],"ename":"ModuleNotFoundError","evalue":"No module named 'cupy'","output_type":"error"}]},{"cell_type":"code","source":"","metadata":{},"execution_count":null,"outputs":[]}]}